# -*- coding: utf-8 -*-
"""Python Population Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWf79xT0UV9uoB9_e8BhyFE2uay4Lapt

File to download: USPopulation1.txt
"""

import matplotlib.pyplot as plt

#option 1: Display pop of user inputted year
def option1(inList):
  print("This is option 1")
  year = int(input("Enter the year you would like the population for: "))
  if year >= 1960 and year <= 2022:
    pop_year = inList[year-1960]
    print(f'The population in {year} was {pop_year:,d}')
  else:
    print("Error: No data for the year entered")


#option 2: Display ∆ in pop between 2 user inputted years
def option2(inList):
  print("This is option 2")
  year1 = int(input("Enter a year: "))
  year2 = int(input("Enter another year: "))
  if (year1 >= 1960 and year1 <= 2022) and (year2 >= 1960 and year2 <= 2022):
    pop_year1 = inList[year1 - 1960]
    pop_year2 = inList[year2 - 1960]
    pop_diff = abs(pop_year1 - pop_year2)
    print(f'The population difference between {year1} and {year2} is {pop_diff:,d}')
  else:
    print("Error: No data for the years entered")


#option 3: Display avg. pop in range from user inputted year 1 to user inputted year 2
def option3(inList):
  print("This is option 3")
  year1 = int(input("Enter a year: "))
  year2 = int(input("Enter another year: "))
  if (year1 >= 1960 and year1 <= 2022) and (year2 >= 1960 and year2 <= 2022):
    year_count = abs(year2 - year1) + 1
    min_year = min(year1,year2)
    sum = 0
    for i in range(year_count):
      sum = sum + inList[min_year - 1960 + i]
    avg = sum/year_count
    print(f'The average population betwen {year1} and {year2} is {avg:,.2f}')
  else:
    print("Error: No data for the years entered")


#option 4: Display line graph of pop data between user inputted years
def option4(inList):
  print("This is option 4")
  year1 = int(input("Enter a year: "))
  year2 = int(input("Enter another year: "))
  if (year1 >= 1960 and year1 <= 2022) and (year2 >= 1960 and year2 <= 2022):
    year_count = abs(year2 - year1) + 1
    min_year = min(year1,year2)
    y_pop = []
    x_year = []
    for i in range(year_count):
      y_pop.append(inList[min_year - 1960 + i])
      x_year.append(min_year+i)
    plt.plot(x_year, y_pop)
    plt.title('US Population by Year')
    plt.xlabel('Year')
    plt.ylabel('Population')
    plt.show()
  else:
    print("Error: No data for the years entered")


#option 5: Display scatter plot of pop data between user inputted years
def option5(inList):
  print("This is option 5")
  year1 = int(input("Enter a year: "))
  year2 = int(input("Enter another year: "))
  if (year1 >= 1960 and year1 <= 2022) and (year2 >= 1960 and year2 <= 2022):
    year_count = abs(year2 - year1) + 1
    min_year = min(year1,year2)
    y_pop = []
    x_year = []
    for i in range(year_count):
      y_pop.append(inList[min_year - 1960 + i])
      x_year.append(min_year+i)
    plt.scatter(x_year, y_pop)
    plt.title('US Population by Year')
    plt.xlabel('Year')
    plt.ylabel('Population')
    plt.show()
  else:
    print("Error: No data for the years entered")



def main():
  toContinue = True #boolean controlling the loop

  #Open and read in file USPopulation1.txt.
  import os
  with open("USPopulation1.txt", "r") as data:
    pop = data.read()

  #Save result in a list or other data structure. Convert the values to int.
  pop_list = pop.split("\n")
  pop_list = [int(x) for x in pop_list]

  #Menu
  while toContinue:
    #display the menu
    print()
    print("Select one of the following options:")
    print("1 - Display population for selected year")
    print("2 - Display change in population between two values")
    print("3 - Display the average population for range between two values")
    print("4 - display line graph of population data between two values")
    print("5 - display scatter plot of population data between two values")
    print("6 - Exit")

    choice = input("Select an option:")

    if choice==str(1):
      option1(pop_list)
    elif choice==str(2):
      option2(pop_list)
    elif choice==str(3):
      option3(pop_list)
    elif choice==str(4):
      option4(pop_list)
    elif choice==str(5):
      option5(pop_list)
    else:
      print("Incorrect input")
      print("Program exiting")
      toContinue=False

main()